version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: tracely-db
    environment:
      POSTGRES_USER: tracely_user
      POSTGRES_PASSWORD: tracely_password
      POSTGRES_DB: tracely
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d

  redis:
    image: redis:7-alpine
    container_name: tracely-redis
    ports:
      - "6379:6379"

  prometheus:
    image: prom/prometheus:latest
    container_name: tracely-prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  toxiproxy:
    image: ghcr.io/shopify/toxiproxy:2.5.0
    container_name: tracely-toxiproxy
    ports:
      - "8474:8474"
      - "8666:8666"

volumes:
  postgres_data:
